// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712133948_AddCheckInProfileReviewStatuses")]
    partial class AddCheckInProfileReviewStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_tai_khoan");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_tao");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lan_dang_nhap_cuoi");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau_hash");

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reset_token_het_han");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reset_token_hash");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("kich_hoat")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("VerifiedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email_xac_thuc");

                    b.HasKey("AccountId")
                        .HasName("pk_tai_khoan");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("uq_taikhoan_kh")
                        .HasFilter("[ma_kh] IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("uq_taikhoan_nv")
                        .HasFilter("[ma_nv] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_taikhoan_username");

                    b.HasIndex("RoleId", "Status")
                        .HasDatabaseName("idx_taikhoan_vaitro");

                    b.ToTable("tai_khoan", null, t =>
                        {
                            t.HasCheckConstraint("chk_taikhoan_chusohuu", "([ma_nv] IS NOT NULL AND [ma_kh] IS NULL) OR ([ma_nv] IS NULL AND [ma_kh] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Backend.Models.AdditionalCost", b =>
                {
                    b.Property<string>("AdditionalCostId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_chi_phi");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_chi_phi");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("ReconciliationId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_doi_soat");

                    b.HasKey("AdditionalCostId")
                        .HasName("pk_cpps");

                    b.HasIndex("ReconciliationId");

                    b.ToTable("chi_phi_phat_sinh", null, t =>
                        {
                            t.HasCheckConstraint("chk_cpps_loai", "[loai_chi_phi] IN ('no_tien_thue','dien_nuoc','hu_hong','phat_vi_pham','khac')");

                            t.HasCheckConstraint("chk_cpps_sotien", "[so_tien] >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.AdminAuditLog", b =>
                {
                    b.Property<string>("AuditLogId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nk");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_hanh_dong");

                    b.Property<string>("ActorAccountId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_thuc");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_tri_moi");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_diem")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_tri_cu");

                    b.Property<string>("TargetAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_doi_tuong");

                    b.HasKey("AuditLogId")
                        .HasName("pk_nhat_ky_qt");

                    b.HasIndex("ActionType", "OccurredAt")
                        .HasDatabaseName("idx_nkqt_hanhdong");

                    b.HasIndex("ActorAccountId", "OccurredAt")
                        .HasDatabaseName("idx_nkqt_nguoithuc");

                    b.HasIndex("TargetAccountId", "OccurredAt")
                        .HasDatabaseName("idx_nkqt_doituong");

                    b.ToTable("nhat_ky_quan_tri", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Amenity", b =>
                {
                    b.Property<string>("AmenityId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_tien_nghi");

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_tien_nghi");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mo_ta");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("AmenityId")
                        .HasName("pk_tien_nghi");

                    b.HasIndex("AmenityName")
                        .IsUnique()
                        .HasDatabaseName("uq_tiennghi_ten");

                    b.ToTable("tien_nghi", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_tai_san");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_tai_san");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("tot")
                        .HasColumnName("tinh_trang");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.HasKey("AssetId")
                        .HasName("pk_tai_san");

                    b.HasIndex("RoomId");

                    b.ToTable("tai_san", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Bed", b =>
                {
                    b.Property<string>("BedId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_giuong");

                    b.Property<short>("BedNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("so_thu_tu");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_thue_thang");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("trong")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.HasKey("BedId")
                        .HasName("pk_giuong");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("idx_giuong_phong");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_giuong_tt");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("RoomId", "BedNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_giuong_phong_stt");

                    b.ToTable("giuong", null, t =>
                        {
                            t.HasCheckConstraint("chk_giuong_gia", "[gia_thue_thang] > 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.Branch", b =>
                {
                    b.Property<string>("BranchId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_chi_nhanh");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_chi_nhanh");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("BranchId")
                        .HasName("pk_chi_nhanh");

                    b.ToTable("chi_nhanh", (string)null);
                });

            modelBuilder.Entity("Backend.Models.CheckoutReport", b =>
                {
                    b.Property<string>("CheckoutReportId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_bb_tra");

                    b.Property<DateOnly>("CheckoutDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tra");

                    b.Property<decimal?>("FinalElectricityReading")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("chi_so_dien_cuoi");

                    b.Property<decimal?>("FinalWaterReading")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("chi_so_nuoc_cuoi");

                    b.Property<bool>("KeysReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_thu_khoa");

                    b.Property<string>("ManagerEmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_quan_ly");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("ReconciliationId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_doi_soat");

                    b.Property<string>("RoomCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tinh_trang_phong");

                    b.HasKey("CheckoutReportId")
                        .HasName("pk_bbtra");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("ReconciliationId")
                        .IsUnique()
                        .HasDatabaseName("uq_bbtra_doisoat");

                    b.ToTable("bien_ban_tra_phong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dia_chi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Việt Nam")
                        .HasColumnName("quoc_tich");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("CustomerId")
                        .HasName("pk_khach_hang");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("uq_kh_cccd");

                    b.ToTable("khach_hang", (string)null);
                });

            modelBuilder.Entity("Backend.Models.DepositBed", b =>
                {
                    b.Property<string>("DepositId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_coc");

                    b.Property<string>("BedId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_giuong");

                    b.HasKey("DepositId", "BedId")
                        .HasName("pk_dcg");

                    b.HasIndex("BedId");

                    b.ToTable("dat_coc_giuong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.DepositSlip", b =>
                {
                    b.Property<string>("DepositId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_coc");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_ho_so");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_lap")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien_coc");

                    b.Property<string>("ManagerEmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_quan_ly");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<DateTime>("PaymentDueAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("han_thanh_toan");

                    b.Property<string>("SalesEmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_sale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("cho_thanh_toan")
                        .HasColumnName("trang_thai");

                    b.HasKey("DepositId")
                        .HasName("pk_phieu_coc");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("SalesEmployeeId");

                    b.ToTable("phieu_dat_coc", null, t =>
                        {
                            t.HasCheckConstraint("chk_coc_sotien", "[so_tien_coc] > 0");

                            t.HasCheckConstraint("chk_coc_trangthai", "[trang_thai] IN ('cho_thanh_toan','hoan_thanh','het_han','huy')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_nv");

                    b.Property<string>("BranchId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_chi_nhanh");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_lam");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vai_tro");

                    b.HasKey("EmployeeId")
                        .HasName("pk_nhan_vien");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_nhanvien_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("Position")
                        .HasDatabaseName("idx_nv_vaitro");

                    b.ToTable("nhan_vien", (string)null);
                });

            modelBuilder.Entity("Backend.Models.HandoverDetail", b =>
                {
                    b.Property<string>("HandoverId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_bb");

                    b.Property<string>("AssetId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_tai_san");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tinh_trang");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<short>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("so_luong");

                    b.HasKey("HandoverId", "AssetId")
                        .HasName("pk_ctbg");

                    b.HasIndex("AssetId");

                    b.ToTable("chi_tiet_ban_giao", (string)null);
                });

            modelBuilder.Entity("Backend.Models.HandoverReport", b =>
                {
                    b.Property<string>("HandoverId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_bb");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hop_dong");

                    b.Property<DateOnly>("HandoverDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ban_giao");

                    b.Property<decimal?>("InitialElectricityReading")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("chi_so_dien_dau");

                    b.Property<decimal?>("InitialWaterReading")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("chi_so_nuoc_dau");

                    b.Property<string>("ManagerEmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_quan_ly");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("RoomCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tinh_trang_phong");

                    b.HasKey("HandoverId")
                        .HasName("pk_bbgiao");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasDatabaseName("uq_bbgiao_hd");

                    b.HasIndex("ManagerEmployeeId");

                    b.ToTable("bien_ban_ban_giao", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hoa_don");

                    b.Property<string>("AccountantEmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_ke_toan");

                    b.Property<string>("BankAccountHolder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chu_tai_khoan");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<DateOnly?>("BillingPeriod")
                        .HasColumnType("date")
                        .HasColumnName("ky_thanh_toan");

                    b.Property<string>("ContractId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hop_dong");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_lap")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<string>("DepositId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_coc");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("thu")
                        .HasColumnName("loai_chung_tu");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_hoa_don");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("chuyen_khoan")
                        .HasColumnName("phuong_thuc");

                    b.Property<string>("ProofImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_minh_chung");

                    b.Property<string>("ReconciliationId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_doi_soat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("cho_thanh_toan")
                        .HasColumnName("trang_thai");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ma_giao_dich");

                    b.HasKey("InvoiceId")
                        .HasName("pk_hoa_don");

                    b.HasIndex("AccountantEmployeeId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DepositId");

                    b.HasIndex("ReconciliationId");

                    b.ToTable("hoa_don", null, t =>
                        {
                            t.HasCheckConstraint("chk_hd2_chungtu", "[loai_chung_tu] IN ('thu','chi')");

                            t.HasCheckConstraint("chk_hd2_loai", "[loai_hoa_don] IN ('tien_coc','tien_thue','dich_vu','hoan_coc','thu_them')");

                            t.HasCheckConstraint("chk_hd2_pt", "[phuong_thuc] IN ('tien_mat','chuyen_khoan')");

                            t.HasCheckConstraint("chk_hd2_trangthai", "[trang_thai] IN ('cho_thanh_toan','da_thanh_toan','huy')");
                        });
                });

            modelBuilder.Entity("Backend.Models.InvoiceServiceDetail", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hoa_don");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_dich_vu");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("thanh_tien");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("so_luong");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("don_gia");

                    b.HasKey("InvoiceId", "ServiceId")
                        .HasName("pk_cthddv");

                    b.HasIndex("ServiceId");

                    b.ToTable("chi_tiet_hoa_don_dich_vu", null, t =>
                        {
                            t.HasCheckConstraint("chk_cthddv_dongia", "[don_gia] >= 0");

                            t.HasCheckConstraint("chk_cthddv_soluong", "[so_luong] > 0");

                            t.HasCheckConstraint("chk_cthddv_thanhtien", "[thanh_tien] >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_thong_bao");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_doc");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("he_thong")
                        .HasColumnName("loai_thong_bao");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_doc");

                    b.Property<string>("RecipientAccountId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_nhan");

                    b.Property<string>("SenderAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_gui");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("NotificationId")
                        .HasName("pk_thong_bao");

                    b.HasIndex("SenderAccountId");

                    b.HasIndex("RecipientAccountId", "IsRead", "CreatedAt")
                        .HasDatabaseName("idx_tb_nguoinhan");

                    b.ToTable("thong_bao", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Permission", b =>
                {
                    b.Property<string>("PermissionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_quyen");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_quyen");

                    b.HasKey("PermissionId")
                        .HasName("pk_quyen_he_thong");

                    b.ToTable("quyen_he_thong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Reconciliation", b =>
                {
                    b.Property<string>("ReconciliationId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_doi_soat");

                    b.Property<string>("AccountantEmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_ke_toan");

                    b.Property<decimal?>("AdditionalPaymentAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien_thu_them");

                    b.Property<decimal>("BaseRefund")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien_hoan_co_ban");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hop_dong");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_lap");

                    b.Property<string>("ManagerEmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_quan_ly");

                    b.Property<decimal>("OriginalDeposit")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien_coc_goc");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien_hoan");

                    b.Property<decimal>("RefundRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ty_le_hoan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("cho_xac_nhan")
                        .HasColumnName("trang_thai");

                    b.Property<decimal>("TotalDeductions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tong_khau_tru");

                    b.HasKey("ReconciliationId")
                        .HasName("pk_doi_soat");

                    b.HasIndex("AccountantEmployeeId");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasDatabaseName("uq_doisoat_hd");

                    b.HasIndex("ManagerEmployeeId");

                    b.ToTable("bang_doi_soat", null, t =>
                        {
                            t.HasCheckConstraint("chk_ds_trangthai", "[trang_thai] IN ('cho_xac_nhan','da_xac_nhan','hoan_tat')");

                            t.HasCheckConstraint("chk_ds_tyle", "[ty_le_hoan] IN (50,70,80,100)");
                        });
                });

            modelBuilder.Entity("Backend.Models.RentalApplication", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_ho_so");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<string>("DesiredArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("khu_vuc_mong_muon");

                    b.Property<string>("DesiredRoomType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_phong_mong_muon");

                    b.Property<DateOnly?>("ExpectedMoveInDate")
                        .HasColumnType("date")
                        .HasColumnName("thoi_gian_du_kien_thue");

                    b.Property<short?>("ExpectedRentalMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("thoi_han_thue_thang");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("LivingSchedule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("gio_giac_sinh_hoat");

                    b.Property<decimal?>("MaximumPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_toi_da");

                    b.Property<decimal?>("MinimumPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_toi_thieu");

                    b.Property<short>("NumberOfPeople")
                        .HasColumnType("smallint")
                        .HasColumnName("so_nguoi");

                    b.Property<string>("OtherRequirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("yeu_cau_khac");

                    b.Property<bool>("RequiresAirConditioner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("yeu_cau_dieu_hoa");

                    b.Property<bool>("RequiresParking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("yeu_cau_gui_xe");

                    b.Property<bool>("RequiresQuietLifestyle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("yeu_cau_yen_tinh");

                    b.Property<string>("SalesEmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_sale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("moi")
                        .HasColumnName("trang_thai");

                    b.HasKey("ApplicationId")
                        .HasName("pk_ho_so");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesEmployeeId");

                    b.ToTable("ho_so_dang_ky", null, t =>
                        {
                            t.HasCheckConstraint("chk_hoso_songuoi", "[so_nguoi] > 0");

                            t.HasCheckConstraint("chk_hoso_trangthai", "[trang_thai] IN ('moi','da_xem_phong','cho_ra_soat_coc','da_dat_coc','cho_kiem_tra_nhan_phong','du_dieu_kien_nhan_phong','huy')");
                        });
                });

            modelBuilder.Entity("Backend.Models.RentalContract", b =>
                {
                    b.Property<string>("ContractId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hop_dong");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<string>("DepositId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_coc");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_thue_thang");

                    b.Property<short>("NumberOfBeds")
                        .HasColumnType("smallint")
                        .HasColumnName("so_giuong_thue");

                    b.Property<string>("PaymentCycle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("hang_thang")
                        .HasColumnName("ky_thanh_toan");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.Property<string>("SalesEmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_sale");

                    b.Property<DateOnly>("SignedDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ky");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("hieu_luc")
                        .HasColumnName("trang_thai");

                    b.HasKey("ContractId")
                        .HasName("pk_hop_dong");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DepositId")
                        .IsUnique()
                        .HasDatabaseName("uq_hopdong_coc");

                    b.HasIndex("RoomId");

                    b.HasIndex("SalesEmployeeId");

                    b.ToTable("hop_dong_thue", null, t =>
                        {
                            t.HasCheckConstraint("chk_hd_trangthai", "[trang_thai] IN ('hieu_luc','het_han','thanh_ly')");
                        });
                });

            modelBuilder.Entity("Backend.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_quyen");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_vai_tro_quyen");

                    b.HasIndex("PermissionId");

                    b.ToTable("vai_tro_quyen", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.Property<string>("AllowedGender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gioi_tinh_cho_phep");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khu_vuc");

                    b.Property<decimal?>("AreaSquareMeters")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("dien_tich_m2");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_chi_nhanh");

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("suc_chua");

                    b.Property<TimeOnly?>("CurfewTime")
                        .HasColumnType("time")
                        .HasColumnName("gio_gioi_nghiem");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<short?>("Floor")
                        .HasColumnType("smallint")
                        .HasColumnName("tang");

                    b.Property<bool>("HasAirConditioner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("co_dieu_hoa");

                    b.Property<bool>("HasParking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("co_gui_xe");

                    b.Property<bool>("RequiresQuietLifestyle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("yeu_cau_yen_tinh");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_phong");

                    b.Property<decimal?>("RoomPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_phong");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_phong");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("trong")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.HasKey("RoomId")
                        .HasName("pk_phong");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("BranchId", "Status")
                        .HasDatabaseName("idx_phong_cn");

                    b.ToTable("phong", null, t =>
                        {
                            t.HasCheckConstraint("chk_phong_suc_chua", "[suc_chua] > 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.RoomAmenity", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.Property<string>("AmenityId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_tien_nghi");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ghi_chu");

                    b.Property<short>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("so_luong");

                    b.HasKey("RoomId", "AmenityId")
                        .HasName("pk_phong_tien_nghi");

                    b.HasIndex("AmenityId");

                    b.ToTable("phong_tien_nghi", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RoomImage", b =>
                {
                    b.Property<string>("RoomImageId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hinh_anh");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("mo_ta");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("thu_tu_hien_thi");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("duong_dan");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("la_anh_dai_dien");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.HasKey("RoomImageId")
                        .HasName("pk_hinh_anh_phong");

                    b.HasIndex("RoomId", "DisplayOrder")
                        .HasDatabaseName("idx_hinhanh_phong_thutu");

                    b.ToTable("hinh_anh_phong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RoomViewingSchedule", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_lich");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_ho_so");

                    b.Property<DateTime>("AppointmentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_gio_hen");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("SalesEmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_sale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("sap_den")
                        .HasColumnName("trang_thai");

                    b.HasKey("ScheduleId")
                        .HasName("pk_lich_xem");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("SalesEmployeeId");

                    b.ToTable("lich_xem_phong", null, t =>
                        {
                            t.HasCheckConstraint("chk_lich_trangthai", "[trang_thai] IN ('sap_den','hoan_thanh','huy')");
                        });
                });

            modelBuilder.Entity("Backend.Models.RoomViewingScheduleRoom", b =>
                {
                    b.Property<string>("ScheduleId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_lich");

                    b.Property<string>("RoomId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.HasKey("ScheduleId", "RoomId")
                        .HasName("pk_lxp");

                    b.HasIndex("RoomId");

                    b.ToTable("lich_xem_phong_phong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Service", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_dich_vu");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_dich_vu");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_dich_vu");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("don_vi_tinh");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("don_gia");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.HasKey("ServiceId")
                        .HasName("pk_dich_vu");

                    b.HasIndex("ServiceName")
                        .IsUnique()
                        .HasDatabaseName("uq_dichvu_ten");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("ServiceType", "IsActive")
                        .HasDatabaseName("idx_dichvu_loai");

                    b.ToTable("dich_vu", null, t =>
                        {
                            t.HasCheckConstraint("chk_dichvu_dongia", "[don_gia] >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.SystemParameter", b =>
                {
                    b.Property<string>("ParameterId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_tham_so");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("kieu_du_lieu");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ParameterGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nhom_tham_so");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_tham_so");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_tri");

                    b.HasKey("ParameterId")
                        .HasName("pk_tham_so_he_thong");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("ParameterGroup", "IsActive")
                        .HasDatabaseName("idx_thamso_nhom");

                    b.ToTable("tham_so_he_thong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.SystemRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("RoleId")
                        .HasName("pk_vai_tro_he_thong");

                    b.ToTable("vai_tro_he_thong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TenantMember", b =>
                {
                    b.Property<string>("TenantMemberId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_tv");

                    b.Property<string>("ApplicationId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_ho_so");

                    b.Property<string>("ContractId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_hop_dong");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("DocumentImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("anh_giay_to");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_giay_to");

                    b.Property<string>("FinancialDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("tai_lieu_tai_chinh");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("gioi_tinh");

                    b.Property<bool>("IsEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("dat_dieu_kien");

                    b.Property<bool>("IsPrimaryTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("la_nguoi_dung_ten");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quoc_tich");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("OccupationOrSchool")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nghe_nghiep_truong_hoc");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dia_chi_thuong_tru");

                    b.Property<string>("RelationshipToPrimary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quan_he_nguoi_dung_ten");

                    b.HasKey("TenantMemberId")
                        .HasName("pk_thanh_vien");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CustomerId");

                    b.ToTable("thanh_vien_thue", null, t =>
                        {
                            t.HasCheckConstraint("chk_tv_gioitinh", "[gioi_tinh] IS NULL OR [gioi_tinh] IN ('Nam','Nu')");
                        });
                });

            modelBuilder.Entity("Backend.Models.Account", b =>
                {
                    b.HasOne("Backend.Models.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .HasConstraintName("fk_taikhoan_nguoitao");

                    b.HasOne("Backend.Models.Customer", "Customer")
                        .WithOne("Account")
                        .HasForeignKey("Backend.Models.Account", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_taikhoan_kh");

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("Backend.Models.Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_taikhoan_nv");

                    b.HasOne("Backend.Models.SystemRole", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_taikhoan_vaitro");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.AdditionalCost", b =>
                {
                    b.HasOne("Backend.Models.Reconciliation", null)
                        .WithMany()
                        .HasForeignKey("ReconciliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cpps_doisoat");
                });

            modelBuilder.Entity("Backend.Models.AdminAuditLog", b =>
                {
                    b.HasOne("Backend.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nkqt_nguoithuc");

                    b.HasOne("Backend.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nkqt_doituong");
                });

            modelBuilder.Entity("Backend.Models.Asset", b =>
                {
                    b.HasOne("Backend.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_taisan_phong");
                });

            modelBuilder.Entity("Backend.Models.Bed", b =>
                {
                    b.HasOne("Backend.Models.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_giuong_phong");

                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_giuong_nguoisua");

                    b.Navigation("Room");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.CheckoutReport", b =>
                {
                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bbtra_quanly");

                    b.HasOne("Backend.Models.Reconciliation", null)
                        .WithMany()
                        .HasForeignKey("ReconciliationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bbtra_doisoat");
                });

            modelBuilder.Entity("Backend.Models.DepositBed", b =>
                {
                    b.HasOne("Backend.Models.Bed", null)
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dcg_giuong");

                    b.HasOne("Backend.Models.DepositSlip", null)
                        .WithMany()
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dcg_coc");
                });

            modelBuilder.Entity("Backend.Models.DepositSlip", b =>
                {
                    b.HasOne("Backend.Models.RentalApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coc_hoso");

                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_coc_quanly");

                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("SalesEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coc_sale");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasOne("Backend.Models.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nhanvien_chinhanh");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Backend.Models.HandoverDetail", b =>
                {
                    b.HasOne("Backend.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ctbg_taisan");

                    b.HasOne("Backend.Models.HandoverReport", null)
                        .WithMany()
                        .HasForeignKey("HandoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctbg_bb");
                });

            modelBuilder.Entity("Backend.Models.HandoverReport", b =>
                {
                    b.HasOne("Backend.Models.RentalContract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bbgiao_hd");

                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bbgiao_ql");
                });

            modelBuilder.Entity("Backend.Models.Invoice", b =>
                {
                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("AccountantEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hd2_ketoan");

                    b.HasOne("Backend.Models.RentalContract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_hd2_hopdong");

                    b.HasOne("Backend.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hd2_kh");

                    b.HasOne("Backend.Models.DepositSlip", null)
                        .WithMany()
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hd2_coc");

                    b.HasOne("Backend.Models.Reconciliation", null)
                        .WithMany()
                        .HasForeignKey("ReconciliationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_hd2_doisoat");
                });

            modelBuilder.Entity("Backend.Models.InvoiceServiceDetail", b =>
                {
                    b.HasOne("Backend.Models.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cthddv_hoadon");

                    b.HasOne("Backend.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cthddv_dichvu");
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.HasOne("Backend.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_nguoinhan");

                    b.HasOne("Backend.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("SenderAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_tb_nguoigui");
                });

            modelBuilder.Entity("Backend.Models.Reconciliation", b =>
                {
                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("AccountantEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ds_ketoan");

                    b.HasOne("Backend.Models.RentalContract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ds_hopdong");

                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ds_quanly");
                });

            modelBuilder.Entity("Backend.Models.RentalApplication", b =>
                {
                    b.HasOne("Backend.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hoso_kh");

                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("SalesEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hoso_sale");
                });

            modelBuilder.Entity("Backend.Models.RentalContract", b =>
                {
                    b.HasOne("Backend.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hd_kh");

                    b.HasOne("Backend.Models.DepositSlip", null)
                        .WithMany()
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hd_coc");

                    b.HasOne("Backend.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hd_phong");

                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("SalesEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hd_sale");
                });

            modelBuilder.Entity("Backend.Models.RolePermission", b =>
                {
                    b.HasOne("Backend.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vtq_quyen");

                    b.HasOne("Backend.Models.SystemRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vtq_vaitro");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.HasOne("Backend.Models.Branch", "Branch")
                        .WithMany("Rooms")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_phong_chinhanh");

                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_phong_nguoisua");

                    b.Navigation("Branch");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.RoomAmenity", b =>
                {
                    b.HasOne("Backend.Models.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ptn_tiennghi");

                    b.HasOne("Backend.Models.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ptn_phong");

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Backend.Models.RoomImage", b =>
                {
                    b.HasOne("Backend.Models.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hinhanh_phong");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Backend.Models.RoomViewingSchedule", b =>
                {
                    b.HasOne("Backend.Models.RentalApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lichxem_hoso");

                    b.HasOne("Backend.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("SalesEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lichxem_sale");
                });

            modelBuilder.Entity("Backend.Models.RoomViewingScheduleRoom", b =>
                {
                    b.HasOne("Backend.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lxp_phong");

                    b.HasOne("Backend.Models.RoomViewingSchedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lxp_lich");
                });

            modelBuilder.Entity("Backend.Models.Service", b =>
                {
                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_dichvu_nguoisua");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.SystemParameter", b =>
                {
                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_thamso_nguoisua");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.TenantMember", b =>
                {
                    b.HasOne("Backend.Models.RentalApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_tv_hoso");

                    b.HasOne("Backend.Models.RentalContract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tv_hopdong");

                    b.HasOne("Backend.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tv_kh");
                });

            modelBuilder.Entity("Backend.Models.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("Backend.Models.Branch", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("Backend.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("Images");

                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("Backend.Models.SystemRole", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
