// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712092246_AddRentalContract")]
    partial class AddRentalContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_tai_khoan");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_tao");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_nv");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("lan_dang_nhap_cuoi");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau_hash");

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reset_token_het_han");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reset_token_hash");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("kich_hoat")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("VerifiedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email_xac_thuc");

                    b.HasKey("AccountId")
                        .HasName("pk_tai_khoan");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("uq_taikhoan_kh")
                        .HasFilter("[ma_kh] IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("uq_taikhoan_nv")
                        .HasFilter("[ma_nv] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_taikhoan_username");

                    b.HasIndex("RoleId", "Status")
                        .HasDatabaseName("idx_taikhoan_vaitro");

                    b.ToTable("tai_khoan", null, t =>
                        {
                            t.HasCheckConstraint("chk_taikhoan_chusohuu", "([ma_nv] IS NOT NULL AND [ma_kh] IS NULL) OR ([ma_nv] IS NULL AND [ma_kh] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Backend.Models.Bed", b =>
                {
                    b.Property<string>("BedId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_giuong");

                    b.Property<short>("BedNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("so_thu_tu");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_thue_thang");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("trong")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.HasKey("BedId")
                        .HasName("pk_giuong");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("idx_giuong_phong");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_giuong_tt");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("RoomId", "BedNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_giuong_phong_stt");

                    b.ToTable("giuong", null, t =>
                        {
                            t.HasCheckConstraint("chk_giuong_gia", "[gia_thue_thang] > 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.Branch", b =>
                {
                    b.Property<string>("BranchId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_chi_nhanh");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_chi_nhanh");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("BranchId")
                        .HasName("pk_chi_nhanh");

                    b.ToTable("chi_nhanh", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_kh");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dia_chi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Việt Nam")
                        .HasColumnName("quoc_tich");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("CustomerId")
                        .HasName("pk_khach_hang");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("uq_kh_cccd");

                    b.ToTable("khach_hang", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_nv");

                    b.Property<string>("BranchId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_chi_nhanh");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_lam");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vai_tro");

                    b.HasKey("EmployeeId")
                        .HasName("pk_nhan_vien");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_nhanvien_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("Position")
                        .HasDatabaseName("idx_nv_vaitro");

                    b.ToTable("nhan_vien", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Permission", b =>
                {
                    b.Property<string>("PermissionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_quyen");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_quyen");

                    b.HasKey("PermissionId")
                        .HasName("pk_quyen_he_thong");

                    b.ToTable("quyen_he_thong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RentalContract", b =>
                {
                    b.Property<string>("RentalContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BedId")
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByAccountId")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("RentalContractId");

                    b.HasIndex("BedId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UpdatedByAccountId");

                    b.ToTable("RentalContract");
                });

            modelBuilder.Entity("Backend.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_quyen");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_vai_tro_quyen");

                    b.HasIndex("PermissionId");

                    b.ToTable("vai_tro_quyen", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_phong");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khu_vuc");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ma_chi_nhanh");

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("suc_chua");

                    b.Property<bool>("HasAirConditioner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("co_dieu_hoa");

                    b.Property<bool>("HasParking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("co_gui_xe");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_phong");

                    b.Property<decimal?>("RoomPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_phong");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_phong");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("trong")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.HasKey("RoomId")
                        .HasName("pk_phong");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("BranchId", "Status")
                        .HasDatabaseName("idx_phong_cn");

                    b.ToTable("phong", null, t =>
                        {
                            t.HasCheckConstraint("chk_phong_suc_chua", "[suc_chua] > 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.Service", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_dich_vu");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_dich_vu");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("loai_dich_vu");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("don_vi_tinh");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("don_gia");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.HasKey("ServiceId")
                        .HasName("pk_dich_vu");

                    b.HasIndex("ServiceName")
                        .IsUnique()
                        .HasDatabaseName("uq_dichvu_ten");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("ServiceType", "IsActive")
                        .HasDatabaseName("idx_dichvu_loai");

                    b.ToTable("dich_vu", null, t =>
                        {
                            t.HasCheckConstraint("chk_dichvu_dongia", "[don_gia] >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.SystemParameter", b =>
                {
                    b.Property<string>("ParameterId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_tham_so");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("kieu_du_lieu");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ParameterGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nhom_tham_so");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_tham_so");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<string>("UpdatedByAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ma_nguoi_sua");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_tri");

                    b.HasKey("ParameterId")
                        .HasName("pk_tham_so_he_thong");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("ParameterGroup", "IsActive")
                        .HasDatabaseName("idx_thamso_nhom");

                    b.ToTable("tham_so_he_thong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.SystemRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("RoleId")
                        .HasName("pk_vai_tro_he_thong");

                    b.ToTable("vai_tro_he_thong", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Account", b =>
                {
                    b.HasOne("Backend.Models.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .HasConstraintName("fk_taikhoan_nguoitao");

                    b.HasOne("Backend.Models.Customer", "Customer")
                        .WithOne("Account")
                        .HasForeignKey("Backend.Models.Account", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_taikhoan_kh");

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("Backend.Models.Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_taikhoan_nv");

                    b.HasOne("Backend.Models.SystemRole", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_taikhoan_vaitro");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Bed", b =>
                {
                    b.HasOne("Backend.Models.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_giuong_phong");

                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_giuong_nguoisua");

                    b.Navigation("Room");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasOne("Backend.Models.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nhanvien_chinhanh");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Backend.Models.RentalContract", b =>
                {
                    b.HasOne("Backend.Models.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId");

                    b.HasOne("Backend.Models.Customer", "Customer")
                        .WithMany("RentalContracts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Room", "Room")
                        .WithMany("RentalContracts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId");

                    b.Navigation("Bed");

                    b.Navigation("Customer");

                    b.Navigation("Room");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.RolePermission", b =>
                {
                    b.HasOne("Backend.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vtq_quyen");

                    b.HasOne("Backend.Models.SystemRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vtq_vaitro");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.HasOne("Backend.Models.Branch", "Branch")
                        .WithMany("Rooms")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_phong_chinhanh");

                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_phong_nguoisua");

                    b.Navigation("Branch");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.Service", b =>
                {
                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_dichvu_nguoisua");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.SystemParameter", b =>
                {
                    b.HasOne("Backend.Models.Account", "UpdatedByAccount")
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_thamso_nguoisua");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Backend.Models.Branch", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("RentalContracts");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("Backend.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("RentalContracts");
                });

            modelBuilder.Entity("Backend.Models.SystemRole", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
